Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
def init():
    # setup figure
    pass

def update(frame_counter):
    # update figure for new frame
    pass
    
anim = animation.FuncAnimation(fig, update, init_func=init, frames=200, blit=True)

anim.save("animation.mp4", fps=30) # fps = frames per second
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[24], line 9[0m
[1;32m      5[0m [38;5;28;01mdef[39;00m [38;5;21mupdate[39m(frame_counter):
[1;32m      6[0m     [38;5;66;03m# update figure for new frame[39;00m
[1;32m      7[0m     [38;5;28;01mpass[39;00m
[0;32m----> 9[0m anim [38;5;241m=[39m [43manimation[49m[38;5;241m.[39mFuncAnimation(fig, update, init_func[38;5;241m=[39minit, frames[38;5;241m=[39m[38;5;241m200[39m, blit[38;5;241m=[39m[38;5;28;01mTrue[39;00m)
[1;32m     11[0m anim[38;5;241m.[39msave([38;5;124m"[39m[38;5;124manimation.mp4[39m[38;5;124m"[39m, fps[38;5;241m=[39m[38;5;241m30[39m) [38;5;66;03m# fps = frames per second[39;00m

[0;31mNameError[0m: name 'animation' is not defined

